### ISSUE TITLE
Convergence addok + geozones

### ISSUE THREAD

**Issue by jdesboeufs** [sgmap/api-communes#11]

**Comment by tmerlier** [comment]
Cette [**solution**](http://ianhinsdale.com/code/2013/12/08/communicating-between-nodejs-and-python/) me parait intéressante pour connecter api-communes et addok

**Comment by jdesboeufs** [comment]
C'est plus la pertinence de la convergence qu'il faut qu'on étudie.
La solution technique sera plus un emballage HTTP qu'une solution un peu dangereuse comme celle que tu proposes ;)

**Comment by yohanboniface** [comment]
https://github.com/addok/addok-geozones
