### ISSUE TITLE
Investiguer ElasticLunr.js

### ISSUE THREAD

**Issue by jdesboeufs** [sgmap/api-communes#19]
https://github.com/weixsong/elasticlunr.js

**Comment by ThibautGery** [comment]
Tu devrais en parler avec @Flightan car il partirait sur `lunr.js`(tu es dessus selon ton package.json)

**Comment by jdesboeufs** [comment]
Oui je connais très bien ces solutions, j'ai juste remarqué qu'ElasticLunr proposait depuis peu quelques raffinements que j'aimerai bencher.
On utilise Lunr en production sur api-communes, et ça fonctionne très bien ;)

**Comment by jdesboeufs** [comment]
Pas de support du _partial word matching_ :(
