### ISSUE TITLE
Ajout des départements

### ISSUE THREAD

**Issue by jdesboeufs** [sgmap/api-communes#7]
## Départements
- [ ] Ajout du département de rattachement pour chaque commune
- [ ] Possibilité de restreindre la recherche de commune à un département
- [ ] Route `/departements?` => Rechercher des départements 
- [ ] Route `/departements/{code}` => Obtenir les informations d'un département
- [ ] Route `/departements/{code}/communes` => Lister les communes d'une région

**Comment by tmerlier** [comment]
Turn to Epic
