### ISSUE TITLE
Noms des régions obsolète

### ISSUE THREAD

**Issue by jdesboeufs** [sgmap/api-communes#70]
Les noms des régions ne prennent pas en compte le décret de renommage lié à la réforme territoriale.

Ping @MattiSG

**Comment by MattiSG** [comment]
cc @seiteta

**Comment by jdesboeufs** [comment]
Le fichier INSEE 2017 ne sera vraisemblablement pas publié avant avril, donc on peut rapatrier le fichier dans le dépôt et le modifier à la main.

**Comment by seiteta** [comment]
@MattiSG : c'est pas moi qui ai posé la question hier (mais ça fait plaisir de voir votre réactivité !)
Pour ma part, je n'ai aucun doute quand aux bénéfices des APIs :smile:

**Comment by MattiSG** [comment]
@seiteta yes, mais tu es le premier EIG dont le handle GitHub correspondait au handle Twitter  😛 Si tu en as d'autres à pinger, go ! ✌️

**Comment by seiteta** [comment]
> tu es le premier EIG dont le handle GitHub correspondait au handle Twitter
La base ! Du coup j'ai pris pour tous les autres :grin:

Pour info, on est (presque) tous là : https://github.com/eig-2017

**Comment by MattiSG** [comment]
@seiteta Bande de nazes  😛

![capture d ecran 2017-01-27 a 12 27 58](https://cloud.githubusercontent.com/assets/222463/22369421/0f0f3c42-e48c-11e6-99fe-95a2c3db8b7a.png)

(je supprimerai ce commentaire par la suite, pas par honte mais parce que cette issue devient le bordel)

**Comment by MattiSG** [comment]
https://github.com/eig-2017/sidenotes/issues/1

**Comment by jdesboeufs** [comment]
Le bordel est toléré ici :)
Le ven. 27 janv. 2017 à 12:30, Matti Schneider <notifications@github.com> a
écrit :

**Comment by jdesboeufs** [comment]
Déploiement en production terminé.
