### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by jdesboeufs** [sgmap/api-communes#8]
- [x] Ajout d'un `Dockerfile`
- [x] <del>Publier sur [Docker Hub](https://hub.docker.com)</del> Superseeded by #21 
- [x] Documenter l'utilisation

**Comment by jdesboeufs** [comment]
@tmerlier demande de l'aide à @ThibautGery ;)

**Comment by ThibautGery** [comment]
Haan la balance ! Je suis là cette après midi !
